apiVersion: v1
kind: Service
metadata:
  name: grpc-nodeport-svc
spec:
  type: NodePort
  selector:
    app: grpc-client-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30030